const webpack = require('webpack');
const cssnano = require('cssnano');
const glob = require('glob');
const path = require('path');
const fs = require('fs');

const WebpackBar = require('webpackbar');
const HTMLWebpackPlugin = require('html-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const WebappWebpackPlugin = require('webapp-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
// const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const RobotstxtPlugin = require('robotstxt-webpack-plugin');
const SitemapPlugin = require('sitemap-webpack-plugin').default;

// config site 
const config = require('../config.site');

const hmr = new webpack.HotModuleReplacementPlugin();

// Optimize CSS assets
const optimizeCss = new OptimizeCssAssetsPlugin({
	assetNameRegExp: /\.css$/g,
	cssProcessor: cssnano,
	cssProcessorPluginOptions: {
	  preset: [
		'default',
      {
        discardComments: {
        removeAll: true,
        },
      },
	  ],
	},
	canPrint: true,
});

// Generate HTML to dist folder (folder distribution)
const paths = [];
const generateHTMLPlugins = () => glob.sync('./src/**/*.html').map((dir) => {
  const filename = path.basename(dir);

  if (filename !== '404.html') {
    paths.push(filename);
  }

  return new HTMLWebpackPlugin({
    title: config.site_name,
    filename,
    template: path.join(config.root, config.paths.src, filename),
    meta: {
      authors: config.site_authors,
      viewport: config.viewport,
      keywords: config.site_keywords,
      description: config.site_description
    },
    minify: {
      collapseWhitespace: config.env === 'production ' ? true : false,
      removeComments: config.env === 'production ' ? true : false,
      removeRedundantAttributes: false,
      removeScriptTypeAttributes: false,
      removeStyleLinkTypeAttributes: false,
      useShortDoctype: false
    },
    hash: true
  });
});

// Webpack bar
const webpackBar = new WebpackBar({
  color: '#ff6469',
});

// Clean webpack
const clean = new CleanWebpackPlugin();


// Extract CSS
const cssExtract = new MiniCssExtractPlugin({
  filename: 'style.[contenthash].css',
});

// Sitemap
const sitemap = new SitemapPlugin(config.site_url, paths, {
	priority: 1.0,
	lastmodrealtime: true,
});

// Generate robots.txt
const robots = new RobotstxtPlugin({
  sitemap: `${config.site_url}/sitemap.xml`,
  host: config.site_url,
});

// Favicons
const favicons = new WebappWebpackPlugin({
  logo: config.favicon,
  prefix: 'images/favicon',
  favicons: {
    developerName: null,
    developerURL: null,
    icons: {
      android: true,
      appleIcon: true,
      appleStartup: false,
      coast: false,
      favicons: true,
      firefox: false,
      windows: false,
      yandex: false,
    },
  },
});

const copyAssetToDist = new CopyWebpackPlugin([
  {
    from: 'assets/*/**/**',
    to: '',
  },
]);

// const favicons = new FaviconsWebpackPlugin({
//     // Your source logo (required)
//     logo: config.favicon,
//     // Enable caching and optionally specify the path to store cached data
//     // Note: disabling caching may increase build times considerably
//     cache: true,
//     // Override the publicPath option usually read from webpack configuration
//     publicPath: '/src/assets',
//     // The directory to output the assets relative to the webpack output dir.
//     // Relative string paths are allowed here ie '../public/static'. If this
//     // option is not set, `prefix` is used.
//     outputPath: '/public/static',
//     // Prefix path for generated assets
//     prefix: 'assets/',
//     // Inject html links/metadata (requires html-webpack-plugin).
//     // This option accepts arguments of different types:
//     //  * boolean
//     //    `false`: disables injection
//     //    `true`: enables injection if that is not disabled in html-webpack-plugin
//     //  * function
//     //    any predicate that takes an instance of html-webpack-plugin and returns either
//     //    `true` or `false` to control the injection of html metadata for the html files
//     //    generated by this instance.
//     inject: true,
// });

module.exports = [
  clean,
  cssExtract,
	...generateHTMLPlugins(),
  // fs.existsSync(config.favicon) && favicons,
  config.env === 'production' && optimizeCss,
  config.env === 'production' && copyAssetToDist,
  config.env === 'production' && robots,
  config.env === 'production' && sitemap,
  webpackBar,
  config.env === 'development' && hmr,
].filter(Boolean);
